

[env:heltec_wifi_lora_32_V3]

platform = espressif32
board    = heltec_wifi_lora_32_V3
framework = arduino

lib_deps =
  git+https://github.com/jgromes/RadioLib.git #master    ; jgromes RadioLib (includes LoRaWAN_ESP32)
  thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays @ ^4.4.0
  adafruit/Adafruit HTU21DF Library @ ^1.1.2
  paulstoffregen/OneWire @ ^2.3.8
  milesburton/DallasTemperature @ ^4.0.5

  
build_flags =
  -D LORA_DEVICE=SX1262                               ; ensure SX1262 driver
  -D USE_CB_ORIGINAL_JOIN                             ; keep OTAA callback prompt off
  -D RADIOLIB_EXCLUDE_CC1101
  -D RADIOLIB_EXCLUDE_NRF24
  -D RADIOLIB_EXCLUDE_RF69
  -D RADIOLIB_EXCLUDE_SX1231
  -D RADIOLIB_EXCLUDE_SI443X
  -D RADIOLIB_EXCLUDE_RFM2X
  -D RADIOLIB_EXCLUDE_SX127X
  -D RADIOLIB_EXCLUDE_STM32WLX
  -D RADIOLIB_EXCLUDE_SX128X
  -D RADIOLIB_EXCLUDE_AFSK
  -D RADIOLIB_EXCLUDE_AX25
  -D RADIOLIB_EXCLUDE_HELLSCHREIBER
  -D RADIOLIB_EXCLUDE_MORSE
  -D RADIOLIB_EXCLUDE_RTTY
  -D RADIOLIB_EXCLUDE_SSTV
  -D RADIOLIB_EXCLUDE_DIRECT_RECEIVE
  -D RADIOLIB_EXCLUDE_BELL
  -D RADIOLIB_EXCLUDE_APRS
  -D RADIOLIB_EXCLUDE_LR11X0
  -D RADIOLIB_EXCLUDE_FSK4
  -D RADIOLIB_EXCLUDE_PAGER

monitor_speed = 115200
